# oanda information
ACCESS_TOKEN: "YOUR-ACCESS-TOKEN"
ACCOUNT_ID: "YOUR-ACCOUNT-ID"

# basic initialization params
START_DATE: "2021-06-03"
END_DATE: "2024-01-07"
GRANULARITY: "M15"
INSTR: "EUR_USD"

# the number of features that we want to do
NUM_FEATURES: 2

# all feature configuration
FEATURE1: "RSI"
FEATURE1_PARAM1_START: 2
FEATURE1_PARAM1_STOP: 20
FEATURE1_PARAM1_STEP: 5
FEATURE1_PARAM2_START: 2
FEATURE1_PARAM2_STOP: 10
FEATURE1_PARAM2_STEP: 5

FEATURE2: "CCI"
FEATURE2_PARAM1_START: 5
FEATURE2_PARAM1_STOP: 20
FEATURE2_PARAM1_STEP: 5
FEATURE2_PARAM2_START: 2
FEATURE2_PARAM2_STOP: 10
FEATURE2_PARAM2_STEP: 5

FEATURE3: "ADX"
FEATURE3_PARAM1_START: 10
FEATURE3_PARAM1_STOP: 11
FEATURE3_PARAM1_STEP: 1
FEATURE3_PARAM2_START: 10
FEATURE3_PARAM2_STOP: 11
FEATURE3_PARAM2_STEP: 1

FEATURE4: "WT"
FEATURE4_PARAM1_START: 10
FEATURE4_PARAM1_STOP: 11
FEATURE4_PARAM1_STEP: 1
FEATURE4_PARAM2_START: 10
FEATURE4_PARAM2_STOP: 11
FEATURE4_PARAM2_STEP: 1


# kernel settings
LOOKBACK_WINDOW_START: 2
LOOKBACK_WINDOW_STOP: 15
LOOKBACK_WINDOW_STEP: 3
WEIGHT_START: 2
WEIGHT_STOP: 15
WEIGHT_STEP: 2
REGRESSION_START: 2
REGRESSION_STOP: 25
REGRESSION_STEP: 5


# regime threshold
REGIME_START: -1.0
REGIME_STOP: 1 
REGIME_STEP: 0.2

